GET http://localhost:4000/VerVehiculos

###
# 2. Crear un cliente
###
POST http://localhost:4000/CrearClientes
Content-Type: application/json

{
    "Identificacion" : "305420908",
    "Nombre": "Brandon",
    "Contrasena": "123456",
    "IdTipoCliente": "1",
    "Telefono": "54879630",
    "Direccion": "Juan viñas"
}
###
#3. Verificar un Usuario
###
POST http://localhost:4000/ValidarCliente
Content-Type: application/json

{
    "Identificacion": "508740802",
    "Contrasena": "123456"
}
###
#4. Ver Detalle del Vehiculo
###
GET http://localhost:4000/vehiculoDetallesID/3

###
#4. eliminar un cliente
###
DELETE http://localhost:4000/EliminarClientes/37


###
#5. Actualizar un cliente
###
PUT http://localhost:4000/ActualizarClientes/24
Content-Type: application/json

{
    "nombre": "Luis",
    "cedula": "902140865",
    "Correo": "Ejemplo@gmail.com"
}

###
POST http://localhost:4000/AgregarNuevoVehiculo
Content-Type: application/json

{
    "IdMarca":  "1",
    "Modelo": "ABC123",
    "idTipo_Vehiculo": "1",
    "Color": "azul",
    "Placa": "2019",
    "Capacidad_Pasajeros": "2",
    "PrecioAlquilerDia": "20000",
    "IdTipoCombustible": "1"
}