GET http://localhost:4000/VerVehiculos

###
# 2. Crear un cliente
###
POST http://localhost:4000/CrearClientes
Content-Type: application/json

{
    "Identificacion" : "305420908",
    "Nombre": "Brandon",
    "Contrasena": "123456",
    "IdTipoCliente": "1",
    "Telefono": "54879630",
    "Direccion": "Juan viñas"
}
###
#3. Verificar un Usuario
###
POST http://localhost:4000/ValidarCliente
Content-Type: application/json

{
    "Identificacion": "5087408010",
    "Contrasena": "14789"
}
###
#4. Ver Detalle del Vehiculo
###
GET http://localhost:4000/vehiculoDetallesID/3

###
#4. eliminar un cliente
###
DELETE http://localhost:4000/EliminarClientes/37


###
#5. Actualizar un cliente
###
POST http://localhost:4000/ReservarAuto/3
Content-Type: application/json

{
    "Numero_Tarjeta": "Luis",
    "Tipo_Tarjeta": "2",
    "Fecha_Vencimiento": "2024-05-09",
    "Nombre_Titular": "Brandon Mora",
    "Precio_Total": "600",
    "Seguro_Vehiculo": "1"
}

###
POST http://localhost:4000/ReserveDia
Content-Type: application/json

{
    "FechaRecoger": "2024-05-03",
    "FechaEntrega": "2024-05-09"
}